---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jacobspl/public_html/padel
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp frontend/*.html $DEPLOYPATH
    - /bin/cp backend/firebase-config.js $DEPLOYPATH
    - /bin/cp backend/point_api.php $DEPLOYPATH
    - /bin/cp backend/service-worker.js $DEPLOYPATH
