---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jacobspl/public_html/padel
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp frontend/*.html $DEPLOYPATH
    - /bin/cp frontend/firebase-config.js $DEPLOYPATH
    - /bin/cp frontend/point_api.php $DEPLOYPATH
    - /bin/cp frontend/service-worker.js $DEPLOYPATH
